version: '3.8'

services:
  stream:
    image: ghcr.io/symmetricresearch/scu-stream:latest
    build:
      context: ./images/stream
      dockerfile: Dockerfile
    volumes:
      - ../results:/output
    
  hpcg:
    image: ghcr.io/symmetricresearch/scu-hpcg:latest
    build:
      context: ./images/hpcg
      dockerfile: Dockerfile
    volumes:
      - ../results:/output
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    
  mini-mlperf:
    image: ghcr.io/symmetricresearch/scu-mini-mlperf:latest
    build:
      context: ./images/mini-mlperf
      dockerfile: Dockerfile
    volumes:
      - ../results:/output
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all