name: Nightly Full Benchmarks (Local GPU)

on:
  schedule:
    - cron: '0 2 * * *'   # 02:00 UTC daily
  workflow_dispatch:

jobs:
  full-bench:
    runs-on: [self-hosted, scu-ci, gpu]
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v4
      - name: Build benchmark containers locally
        run: |
          cd benchmarks/images/stream && docker build -t scu-stream:latest .
          cd ../hpcg && docker build -t scu-hpcg:latest .
          cd ../mini-mlperf && docker build -t scu-mini-mlperf:latest .
      - name: Run STREAM, HPCG, Mini-MLPerf
        run: |
          bash benchmarks/run_all_direct.sh --full
      - name: Sign results (SHA256 + Ed25519)
        run: |
          ./scripts/sign_artifacts.sh auto
          ./scripts/ed25519_sign.sh auto
      - name: Generate cost report
        run: |
          RESULTS_DIR=$(ls -d results/*/ 2>/dev/null | sort -Vr | head -n1)
          ./scripts/cost_report.sh > "${RESULTS_DIR}/cost_report.txt"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: full-bench-results-${{ github.run_id }}
          path: results/