name: Build and Push Containers

on:
  workflow_dispatch:
  push:
    paths:
      - 'benchmarks/images/**'
      - '.github/workflows/build-and-push.yml'

jobs:
  build-push:
    runs-on: [self-hosted, scu-ci, gpu]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      
      - name: Build STREAM (verification only)
        run: |
          cd benchmarks/images/stream
          docker build -t scu-stream:test .
          echo "✅ STREAM container builds successfully with large-array support"
          
      - name: Build HPCG (verification only)
        run: |
          cd benchmarks/images/hpcg
          docker build -t scu-hpcg:test .
          echo "✅ HPCG container builds successfully"
          
      - name: Build Mini-MLPerf (verification only)
        run: |
          cd benchmarks/images/mini-mlperf
          docker build -t scu-mini-mlperf:test .
          echo "✅ Mini-MLPerf container builds successfully"
          
      - name: Verify builds completed
        run: |
          echo "All container builds verified successfully:"
          echo "- STREAM (with large-array support)"
          echo "- HPCG" 
          echo "- Mini-MLPerf"