name: Test Local GPU Runner

on:
  workflow_dispatch:

jobs:
  test-gpu:
    runs-on: [self-hosted, scu-ci, gpu]
    timeout-minutes: 5
    steps:
      - name: System Check
        run: |
          echo "=== Runner System Info ==="
          hostname
          whoami
          uptime
          
      - name: GPU Detection
        run: |
          echo "=== GPU Detection ==="
          nvidia-smi --query-gpu=name,driver_version,memory.total --format=csv
          
      - name: Docker Verification
        run: |
          echo "=== Docker Status ==="
          docker --version
          docker ps
          
      - name: Runner Success
        run: |
          echo "✅ scu-local-3080 runner is operational!"
          echo "Ready for benchmark workloads"